# Generated by Django 4.2.5 on 2023-09-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
