# Generated by Django 4.2.5 on 2023-09-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frequencia', '0002_alter_cadastro_aluno_data_de_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_aluno',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=11),
        ),
        migrations.AddField(
            model_name='cadastro_aluno',
            name='turno',
            field=models.CharField(blank=True, choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=11),
        ),
    ]
