# Generated by Django 4.2.5 on 2023-09-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frequencia', '0003_cadastro_aluno_sexo_cadastro_aluno_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_aluno',
            name='turma',
            field=models.CharField(blank=True, choices=[('1', 'A'), ('1', 'B'), ('1', 'C'), ('2', 'A'), ('2', 'B'), ('2', 'C'), ('3', 'A'), ('3', 'B'), ('3', 'C')], max_length=11),
        ),
    ]
