# Generated by Django 4.2.5 on 2023-09-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frequencia', '0004_cadastro_aluno_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_aluno',
            name='turma',
            field=models.CharField(blank=True, choices=[('1', '1-A'), ('2', '1-B'), ('3', '1-C'), ('4', '2-A'), ('5', '2-B'), ('6', '2-C'), ('7', '3-A'), ('8', '3-B'), ('9', '3-C')], max_length=11),
        ),
    ]
