# Generated by Django 4.2.5 on 2023-09-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frequencia', '0005_alter_cadastro_aluno_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_aluno',
            name='telefone',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
