# Generated by Django 4.2.5 on 2023-09-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frequencia', '0006_cadastro_aluno_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=10)),
                ('data_de_nascimento', models.DateField()),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=11)),
                ('turno', models.CharField(blank=True, choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=11)),
                ('diciplina', models.CharField(blank=True, choices=[('1', 'português'), ('2', 'matematica'), ('3', 'historia'), ('4', 'geografia'), ('5', 'fisica'), ('6', 'biologia'), ('7', 'ed:fisica'), ('8', 'informatica'), ('9', 'ingles')], max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11)),
            ],
        ),
    ]
