# Generated by Django 4.2.5 on 2023-09-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frequencia', '0007_cadastro_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=10)),
            ],
        ),
    ]
