# Generated by Django 4.2.5 on 2023-09-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_frequencia', '0008_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_aluno',
            name='foto',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro_funcionario',
            name='foto',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
